/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DGIOUtility */

#ifndef _Included_DGIOUtility
#define _Included_DGIOUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DGIOUtility
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_print
  (JNIEnv *, jobject);

/*
 * Class:     DGIOUtility
 * Method:    openDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     DGIOUtility
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     DGIOUtility
 * Method:    printPortCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_printPortCount
  (JNIEnv *, jobject);

/*
 * Class:     DGIOUtility
 * Method:    printPortProperties
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_printPortProperties
  (JNIEnv *, jobject);

/*
 * Class:     DGIOUtility
 * Method:    turnOnLEDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_turnOnLEDs
  (JNIEnv *, jobject);

/*
 * Class:     DGIOUtility
 * Method:    turnOffLEDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DGIOUtility_turnOffLEDs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
