/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DPIOUtility */

#ifndef _Included_DPIOUtility
#define _Included_DPIOUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DPIOUtility
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_print
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    openDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    printPortCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_printPortCount
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    printPortProperties
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_printPortProperties
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    enablePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_enablePort
  (JNIEnv *, jobject, jint);

/*
 * Class:     DPIOUtility
 * Method:    dpioEnableEx
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_dpioEnableEx
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    dpioGetPinMask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_dpioGetPinMask
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    dpioDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_dpioDisable
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    dpioSetPinDirection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_dpioSetPinDirection
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    dpioSetPinState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_dpioSetPinState
  (JNIEnv *, jobject);

/*
 * Class:     DPIOUtility
 * Method:    dpioGetPinState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DPIOUtility_dpioGetPinState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
