/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_printHello
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    printGoodbye
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_printGoodbye
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    openDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    printPortCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_printPortCount
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    printPortProperties
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_printPortProperties
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    enablePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNITest_enablePort
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNITest
 * Method:    readFromPortOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_readFromPortOne
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    dpioEnableEx
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_dpioEnableEx
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    dpioGetPinMask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_dpioGetPinMask
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    dpioDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_dpioDisable
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    dpioSetPinDirection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_dpioSetPinDirection
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    dpioSetPinState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_dpioSetPinState
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    dpioGetPinState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_dpioGetPinState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
